name: optimized_search_field
description: A Flutter package with customizable search fields for large lists, models, and rich content. Includes single and multi-search options with various optimizations.
version: 2.0.0+2
homepage: https://github.com/DemienIlnutskiy/flutter_optimized_search_field

environment:
  sdk: '>=3.19.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: any

flutter:

